# Generated by Django 5.2 on 2025-05-18 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogpedia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('Poodle', '貴賓犬'), ('Chihuahua', '吉娃娃'), ('Pomeranian', '博美犬'), ('Bichon_Frise', '比熊犬'), ('Shiba_Inu', '柴犬'), ('Akita_Inu', '秋田犬')], max_length=50)),
                ('description', models.TextField()),
                ('interest', models.TextField(blank=True, null=True)),
                ('traits', models.TextField(blank=True, null=True)),
                ('care_needs', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='dogs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dogpedia.userpetprofile')),
            ],
        ),
    ]
