# Generated by Django 5.2 on 2025-05-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogpedia', '0002_userpetprofile_petcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='image',
            field=models.ImageField(upload_to='dogs'),
        ),
        migrations.AlterField(
            model_name='userpetprofile',
            name='image',
            field=models.ImageField(upload_to='dogs'),
        ),
    ]
