# Generated by Django 5.2 on 2025-05-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogpedia', '0003_alter_dogprofile_image_alter_userpetprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcomment',
            name='pet_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dogpedia.dogprofile'),
        ),
    ]
