# Generated by Django 5.2 on 2025-04-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('english_name', models.CharField(max_length=100)),
                ('family_life', models.TextField()),
                ('body_features', models.TextField()),
                ('social_behavior', models.TextField()),
                ('personality', models.TextField()),
                ('cover_image', models.ImageField(upload_to='breeds/')),
            ],
        ),
        migrations.CreateModel(
            name='SugarGlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gliders/')),
            ],
        ),
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dogs/')),
                ('profile', models.TextField()),
                ('interests', models.TextField()),
                ('traits', models.TextField()),
                ('care', models.TextField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='dogpedia.dogbreed')),
            ],
        ),
    ]
